//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicesOfBeautySalon.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registration
    {
        public long ID { get; set; }
        public long RegisterUserID { get; set; }
        public long BeautySalonServiceID { get; set; }
        public System.DateTime Day { get; set; }
        public System.TimeSpan StartTime { get; set; }
        public System.TimeSpan EndTime { get; set; }
    
        public virtual BeautySalonService BeautySalonService { get; set; }
        public virtual User User { get; set; }
    }
}
